"use client";
// import type { Metadata } from "next";
import "./globals.css";

import AOS from "aos";
import "aos/dist/aos.css";

import Navbar from "~/components/Navbar";
import Footer from "~/components/Footer";
import { useEffect } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    AOS.init({
      once: true,
      duration: 600,
      easing: "ease-out-sine",
    });
  }, []);

  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <link rel="icon" href="/favicon/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <title>UNLV AI & Data Science Club</title>
        <meta
          name="description"
          content="Join us to explore the latest in AI and data science at UNLV. Participate in events, workshops, and networking opportunities."
        />

        <meta property="og:title" content="AI & Data Science Club at UNLV" />
        <meta
          property="og:description"
          content="Join us to explore the latest in AI and data science at UNLV. Participate in events, workshops, and networking opportunities."
        />
        <meta
          property="og:image"
          content="https://aiunlv.vercel.app/AIDataScience_Image.webp"
        />
        <meta property="og:url" content="https://aiunlv.vercel.app" />
        <meta property="og:site_name" content="AI Data Science Club" />
        <meta property="og:type" content="website" />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="UNLV AI & Data Science Club" />
        <meta
          name="twitter:description"
          content="Join us to explore the latest in AI and data science at UNLV. Participate in events, workshops, and networking opportunities."
        />
        <meta
          name="twitter:image"
          content="https://aiunlv.vercel.app/AIDataScience_Image.webp"
        />

        <link rel="canonical" href="https://aiunlv.vercel.app" />
        <meta name="robots" content="index, follow" />

        <link rel="preload" as="image" href="/images/image-1.webp" />
        <link rel="preload" as="image" href="/images/image-3.webp" />
      </head>
      <body className={`antialiased`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
